version: 2.1
jobs:
  build_and_push_docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-app .
      - run:
          name: Docker Login to DockerHub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Tag Docker Image
          command: docker tag hello-world-app:latest $DOCKERHUB_USERNAME/hello-world-app:latest
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/hello-world-app:latest

workflows:
  build_and_push:
    jobs:
      - build_and_push_docker
